name: Hanako
description: $description
version: '${version}'

main: pt.starfall.hanako.Hanako
api-version: '26.1.2'
load: POSTWORLD
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true

authors: [ taigumimiss ]
